# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='joiner',
        ),
        migrations.AddField(
            model_name='travel',
            name='joiner',
            field=models.ManyToManyField(related_name='joined_travels', to='travel_buddy_app.User'),
        ),
    ]
